<!DOCTYPE html>
<html>
    <head>
        <title>Задание №15</title>
        <link href="/tasks/task-15/style.css" type="text/css" rel="stylesheet">  
    </head>

    <body>
        <pre>
        <?
        	$array = [1,-1,2,-2,-5,4];
        	function zeroAftNegNum($array) {
				for ($i = 0; $i < count($array); $i++) { 
					if ($array[$i] < 0) {
						array_splice($array, $i + 1, 0, 0);
					}
				}
				return $array;
			}
			print_r(zeroAftNegNum($array));
        ?>
        </pre>
    </body>

</html>


