<!DOCTYPE html>
<html>
    <head>
        <title>Задание №12</title>
        <link href="/tasks/task-12/style.css" type="text/css" rel="stylesheet">  
    </head>

    <body>
        <pre>
        <?
        	$array = [1,1,1,2,2,2,3,3,3];
        	function unique($array) {
        		$array2 = array();
        		foreach ($array as $key => $value) {
        				$array2[$value] = $value;
        		}

        		return array_values($array2);
        	}
        	print_r (unique($array));
        ?>
        </pre>
    </body>

</html>


