<!DOCTYPE html>
<html>
    <head>
        <title>Массивы в PHP</title>
        <link href="/tasks/task-3/style.css" type="text/css" rel="stylesheet">  
    </head>

    <body>
        <pre>
        <?
        $array = [1,2,3,4];

        $array2 = [
        	'a' => 1,
        	'b' => 2,
        	'c' => 3
        	];

        var_dump($array[0]);
        var_dump($array{0});
        array_pop($array);
        var_dump($array);
        ?>
        </pre>
    </body>

</html>


