<!DOCTYPE html>
<html>
    <head>
        <title>Задание №9</title>
        <link href="/tasks/task-9/style.css" type="text/css" rel="stylesheet">  
    </head>

    <body>
        <pre>
        <?
        	$a = 12;
        	$b = 9;
        	function sum($a, $b)
        	{
        		if ($a > $b) {
        			echo 'Сумма не существует!';
        		} else echo $a+$b;
        	}
        	sum($a, $b);
        ?>
        </pre>
    </body>

</html>


