<?php

$links = [
    '<a href="http://example.com/example/">link example</a>',
    '<a class="link" href="http://php36.loc/task-list/">to all tasks</a>',
    '<a href="https://www.facebook.com/realfive/" title="hello">real on facebook</a>',
    '<a href="http://realfive.eu/" class="link">real site</a>',
];
$pattern = '/href="([^"]+)/';
$links = serialize($links);

preg_match_all($pattern, $links, $matches);
echo '<pre>';
print_r($matches[1]);