<!DOCTYPE html>
<html>
    <head>
        <title>Задание №10</title>
        <link href="/tasks/task-10/style.css" type="text/css" rel="stylesheet">  
    </head>

    <body>
        <pre>
        <?
        	$n = 45;
        	function n( $n ) 
        	{
        		for ($i = 0; $i < $n; $i++) {

        			if((strpos($i , '3') !== false) AND ($i % 5 != 0)) {
        				echo $i, '<br>';
        			}
        		}
        	}

        	n($n);
        ?>
        </pre>
    </body>

</html>



